const months=[
  {month:'Marzo',amount:59.90,status:'Pagado',note:'Plan Móvil 40 GB',extra:0},
  {month:'Abril',amount:59.90,status:'Pagado',note:'Plan Móvil 40 GB',extra:0},
  {month:'Mayo',amount:62.40,status:'Pagado',note:'Plan + Protección Móvil prorrateada',extra:2.50},
  {month:'Junio',amount:59.90,status:'Pagado',note:'Plan Móvil 40 GB',extra:0},
  {month:'Julio',amount:59.90,status:'Pagado',note:'Plan Móvil 40 GB',extra:0},
  {month:'Agosto',amount:62.40,status:'Pendiente',note:'Plan + prorrateo',extra:2.50}
];
const concepts=[
  ['Prorrateo','Es cobrar solo la parte proporcional de un servicio por los días que estuvo activo.','Si un servicio cuesta S/15 al mes pero estuvo activo solo algunos días, el recibo muestra únicamente la parte correspondiente.'],
  ['Reconexión','Es un cargo asociado a volver a activar un servicio después de una suspensión.','Debe existir una orden o movimiento que permita explicar cuándo y por qué ocurrió la reactivación.'],
  ['Fin de descuento','Una promoción puede terminar y el recibo vuelve al precio habitual, sin que el plan haya subido.','Julio: plan S/59.90 con descuento. Agosto: termina el descuento y vuelve la tarifa regular.'],
  ['Cambio de plan','Si cambias de plan dentro del ciclo, pueden aparecer importes proporcionales del plan anterior y del nuevo.','LucIA debe separar qué días corresponden a cada plan y mostrar la diferencia.'],
  ['Cuota de equipo','Es la cuota mensual de un equipo financiado y va separada del precio del plan.','El recibo puede mostrar Plan S/59.90 + cuota de equipo S/XX.XX.'],
  ['Nota de crédito','Es un ajuste a favor del cliente que reduce o corrige un monto facturado.','Puede aparecer como importe negativo y debe poder relacionarse con la corrección que lo originó.'],
  ['Cargo único','Es un cobro que ocurre una sola vez y no debería repetirse cada mes.','Instalación, activación u otro concepto puntual, siempre que exista evidencia.'],
  ['Cargo recurrente','Es un cobro que se repite mientras el servicio o suscripción siga activo.','Un servicio adicional mensual debe aparecer de forma consistente en los ciclos siguientes.'],
  ['Renta adelantada','El periodo de servicio se cobra al inicio del ciclo.','El recibo cubre el periodo que vas a utilizar, según la modalidad de facturación.'],
  ['Renta vencida','El periodo de servicio se cobra después de haber sido utilizado.','El recibo refleja un periodo ya consumido, según la modalidad del producto.']
];
const pages=document.querySelectorAll('.page');
function nav(name){pages.forEach(p=>p.classList.toggle('active',p.id===`page-${name}`));document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));
const bars=document.getElementById('bars'); months.forEach((m,i)=>{const wrap=document.createElement('div');wrap.className='bar-wrap'+(i===months.length-1?' current':'');const h=72+(m.amount-59.9)*25;wrap.innerHTML=`<span class="bar-value">S/${m.amount.toFixed(2)}</span><div class="bar" style="height:${h}%"></div><span class="bar-label">${m.month.slice(0,3)}</span>`;bars.appendChild(wrap)});
const grid=document.getElementById('receiptGrid'); months.forEach((m,i)=>{const card=document.createElement('article');card.className='receipt-card'+(i===months.length-1?' current':'');card.innerHTML=`<div class="receipt-top"><span class="eyebrow">${m.month.toUpperCase()} 2026</span><span class="status-chip ${m.status==='Pendiente'?'pending':''}">${m.status}</span></div><strong>S/${m.amount.toFixed(2)}</strong><small>${m.note}</small><button class="text-btn" data-receipt="${m.month}">Ver ficha del mes →</button>`;grid.appendChild(card)});
const cgrid=document.getElementById('conceptGrid'); concepts.forEach(([t,d,e],idx)=>{const el=document.createElement('article');el.className='concept';el.innerHTML=`<button><div><span class="eyebrow">CONCEPTO ${String(idx+1).padStart(2,'0')}</span>${t}</div><span>+</span></button><div class="concept-body">${d}<div class="concept-example"><strong>Ejemplo sencillo:</strong><br>${e}</div><button class="text-btn concept-chat" style="padding:10px 0 0">Explícamelo con mi recibo →</button></div>`;el.querySelector('button').addEventListener('click',()=>{el.classList.toggle('open');el.querySelector('button>span').textContent=el.classList.contains('open')?'−':'+'});el.querySelector('.concept-chat').addEventListener('click',()=>openChat(`Explícame ${t.toLowerCase()} con mi recibo`));cgrid.appendChild(el)});
const trace=document.getElementById('traceModal');document.getElementById('openTrace').onclick=()=>trace.hidden=false;document.querySelectorAll('[data-close-modal]').forEach(b=>b.onclick=()=>trace.hidden=true);trace.addEventListener('click',e=>{if(e.target===trace)trace.hidden=true});
const rmodal=document.getElementById('receiptModal'),rcontent=document.getElementById('receiptContent');
function openReceipt(name){const m=months.find(x=>x.month===name)||months.at(-1);const previous=name==='Agosto'?'Julio':null;rcontent.innerHTML=`<div class="receipt-sheet"><div class="receipt-sheet-head"><div><span class="eyebrow">FICHA DEL RECIBO</span><h2>${m.month} 2026</h2></div><span class="status-chip ${m.status==='Pendiente'?'pending':''}">${m.status}</span></div><div class="big">S/${m.amount.toFixed(2)}</div><div class="receipt-line"><span>Plan Móvil 40 GB</span><strong>S/59.90</strong></div>${m.extra?`<div class="receipt-line"><span>Protección Móvil · prorrateo</span><strong>+ S/${m.extra.toFixed(2)}</strong></div>`:''}<div class="receipt-line"><span>Total</span><strong>S/${m.amount.toFixed(2)}</strong></div><div class="receipt-note">${m.extra?'Este mes tiene un cargo proporcional adicional. El plan base no cambió.':'No se detectaron cargos adicionales en esta ficha.'}</div>${previous?'<button class="btn primary" style="margin-top:15px" data-jump-trace>Ver cómo se comparó con julio</button>':''}</div>`;rmodal.hidden=false;const j=rcontent.querySelector('[data-jump-trace]');if(j)j.onclick=()=>{rmodal.hidden=true;trace.hidden=false}};
document.addEventListener('click',e=>{const b=e.target.closest('[data-receipt]');if(b){openReceipt(b.dataset.receipt)}});document.querySelectorAll('[data-close-receipt]').forEach(b=>b.onclick=()=>rmodal.hidden=true);rmodal.addEventListener('click',e=>{if(e.target===rmodal)rmodal.hidden=true});
const toast=document.getElementById('toast');function showToast(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
document.querySelectorAll('[data-feedback]').forEach(b=>b.addEventListener('click',()=>{const yes=b.dataset.feedback==='yes';document.getElementById('feedbackResult').textContent=yes?'✓ Guardado: RESUELTO_PRIMER_INTENTO':'LucIA lo reformulará antes de derivarte.';if(yes)showToast('Consulta marcada como resuelta');else openChat('No entendí la explicación')}));
const panel=document.getElementById('chatPanel'),body=document.getElementById('chatBody'),input=document.getElementById('chatInput');function openChat(seed){panel.classList.add('open');panel.setAttribute('aria-hidden','false');if(seed){input.value=seed;setTimeout(()=>document.getElementById('chatForm').requestSubmit(),80)}else input.focus()}document.querySelectorAll('[data-open-chat]').forEach(b=>b.addEventListener('click',()=>openChat()));document.getElementById('closeChat').onclick=()=>{panel.classList.remove('open');panel.setAttribute('aria-hidden','true')};
function answer(q){const s=q.toLowerCase();if(s.includes('no entend')||s.includes('otra forma'))return 'Claro. Piensa que tu plan cuesta S/59.90. Como Protección Móvil estuvo activo solo 5 días, no te cobraron un mes completo: solo S/2.50 por esos días. Por eso el total quedó en S/62.40.';if(s.includes('prorrate'))return 'Prorrateo significa “pagar solo la parte que usaste”. En tu caso, el cargo adicional fue S/2.50 por los días activos de Protección Móvil.';if(s.includes('sub')||s.includes('caro')||s.includes('var'))return 'Tu recibo pasó de S/59.90 a S/62.40. El plan no subió: la diferencia de S/2.50 viene de un prorrateo de Protección Móvil.';if(s.includes('asesor')||s.includes('humano'))return 'Puedo derivar el caso con el resumen, recibos revisados y evidencia para que no repitas tu historia. En esta demo puedes abrir la pestaña “Asesor”.';if(s.includes('nunca')||s.includes('no pedi')||s.includes('no pedí'))return 'No puedo confirmar ese origen con seguridad si falta evidencia. Prefiero detenerme y derivarlo a un asesor antes que inventar una causa.';if(s.includes('reconexion')||s.includes('reconexión'))return 'La reconexión es la reactivación del servicio después de una suspensión. Para afirmarla en un caso real, debe existir una orden o movimiento que la respalde.';return 'Puedo ayudarte a revisar montos, conceptos, fechas y por qué cambió el recibo. Si una causa no está respaldada por evidencia, te lo diré y no inventaré.'}
function send(q){if(!q.trim())return;body.insertAdjacentHTML('beforeend',`<div class="msg user">${q.replace(/[<>]/g,'')}</div>`);input.value='';body.scrollTop=body.scrollHeight;setTimeout(()=>{body.insertAdjacentHTML('beforeend',`<div class="msg bot">${answer(q)}</div>`);body.scrollTop=body.scrollHeight},260)}document.getElementById('chatForm').addEventListener('submit',e=>{e.preventDefault();send(input.value)});document.querySelectorAll('.quick-prompts button').forEach(b=>b.onclick=()=>send(b.textContent));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){trace.hidden=true;rmodal.hidden=true;panel.classList.remove('open')}});
